In [1]:
import numpy as np

In [2]:
p = np.array([9,8,7])
q = np.array([3,2,4])

In [3]:
p + q

array([12, 10, 11])

In [4]:
p - q

array([6, 6, 3])

In [5]:
q - p

array([-6, -6, -3])

In [6]:
p % q

array([0, 0, 3], dtype=int32)

In [7]:
p % 2

array([1, 0, 1], dtype=int32)

In [8]:
p > 8

array([ True, False, False])