In [1]:
import numpy as np

#### Create an array on which we can perform operations
This list contains the cubes of the numbers 0-9

In [2]:
x = np.arange(10)**3

x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### Accessing individual array elements
Just like with Python lists, we access elements by their index which represents their position in the array

In [3]:
x[3]

27

#### Negative index values
This will retrieve the element at the 4th location from the end of the list

In [4]:
x[-4]

216

#### Array slicing
In order to retrieve the elements at index locations 1-7, we specify the slice 1:8. 

In [5]:
x[1 : 8]

array([  1,   8,  27,  64, 125, 216, 343])

#### Negative index values in a slice
This will return elements from index 3 through to index -4

In [6]:
x[3 : -3]

array([ 27,  64, 125, 216])

#### Implicit index when slicing
When the start index is not specified, it's taken to mean that the slice begins at index 0

In [7]:
x[ : 8]

array([  0,   1,   8,  27,  64, 125, 216, 343])

#### No end index specified
It is assumed that the end index is the end of the list

In [8]:
x[3 : ]

array([ 27,  64, 125, 216, 343, 512, 729])

#### The start, stop, step notation in an index

In [9]:
x[ : 10: 2]

array([  0,   8,  64, 216, 512])

#### Negative step values
The step can also be negative in which case we go through the array backwards

In [10]:
x[ ::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

### Accessing elements in 2D arrays
Create an array with a mix of strings and numbers. They all get converted to Unicode strings

In [11]:
companies = np.array([['Samsung','Microsoft','IBM','Spotify','Flipkart'],
                     [1938, 1975, 1911, 2006, 2007],
                     [489000, 131000, 380000, 3000, 30000]])

In [12]:
companies

array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
       ['1938', '1975', '1911', '2006', '2007'],
       ['489000', '131000', '380000', '3000', '30000']], dtype='<U9')

#### Access a row in the array
Since a 2D array is effectively a 1D array of 1D arrays, specifiying a single index will return the 1D array (row) corresponding to that index

In [13]:
companies[0]

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'], dtype='<U9')

#### Access a particular column
Here, we use the slice notation to retrive all rows (everything in the first dimension) and just one column (index 2 in the second dimension)

In [14]:
companies[:, 2]

array(['IBM', '1911', '380000'], dtype='<U9')

#### Specifying two dimensions to retrieve the value in a cell

In [15]:
companies[0, 2]

'IBM'

#### Slicing the 2D array

In [16]:
companies[0:2, 2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006']], dtype='<U9')

In [17]:
companies[:, 2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006'],
       ['380000', '3000']], dtype='<U9')

In [18]:
companies[-1, :]

array(['489000', '131000', '380000', '3000', '30000'], dtype='<U9')

#### Using ellipsis
The three dots are referred to as ellipsis in Python and NumPy. They are special operators which are used to denote "the rest of the array"

In [19]:
companies[0, ...]

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'], dtype='<U9')

In [20]:
companies[..., 2]

array(['IBM', '1911', '380000'], dtype='<U9')