In [1]:
import numpy as np

#### Create an array of 10 elements
These are the cubes of the integers 0-9

In [2]:
x = np.arange(10)**3

x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### Iterate using a for loop
Just like with Python lists, we can iterate over an NDArray with a for loop. 

In [3]:
for i in x:
    print(i)

0
1
8
27
64
125
216
343
512
729


#### Iteraring over 2D NDArrays
Create an array containing the names of some companies along with their year of founding and the number of employees

In [4]:
companies = np.array([['Samsung','Microsoft','IBM','Spotify','Flipkart'],
                     [1938, 1975, 1911, 2006, 2007],
                     [489000, 131000, 380000, 3000, 30000]])

#### Iterating over each row in a 2D array
Using the 2D array directly in a for loop will allow us to iterate over each row

In [5]:
i = 0
for row in companies:
    print('Row', i, ': ',row)
    i += 1

Row 0 :  ['Samsung' 'Microsoft' 'IBM' 'Spotify' 'Flipkart']
Row 1 :  ['1938' '1975' '1911' '2006' '2007']
Row 2 :  ['489000' '131000' '380000' '3000' '30000']


#### The flatten() function
This will convert a multidimensional array into a 1D array. By default the flattened array begins with the first row of the original, then the 2nd row is appended and then the third etc. This is called "row major" or C-style flattening.

In [6]:
companies.flatten()

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart', '1938',
       '1975', '1911', '2006', '2007', '489000', '131000', '380000',
       '3000', '30000'], dtype='<U9')

#### Column major (Fortran-style) flattening
In order for the flattened array to have the columns of the original appended in order, we use F-style flattening. This we can specify in the order argument. The possible values are 'C', 'F', 'A' and 'K'.

In [8]:
for data in companies.flatten(order = 'F'):
    print(data)

Samsung
1938
489000
Microsoft
1975
131000
IBM
1911
380000
Spotify
2006
3000
Flipkart
2007
30000


## nditer
Efficient multi-dimensional iterator object to iterate over arrays

In [9]:
num = np.arange(16).reshape(4,4)

num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
for i in np.nditer(num):
    print(i)  

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


#### Set the order in which to iterate over the array
The default iteration order is C ordering. Here, we use F ordering

In [11]:
for i in np.nditer(num, order = 'F'):
    print(i)  

0
4
8
12
1
5
9
13
2
6
10
14
3
7
11
15


#### Iteration flags
There are several flags which we can pass as a list to nditer. To iterate over each column, we use the flag argument with value 'external_loop'

In [12]:
for i in np.nditer(num, order = 'F', flags = ['external_loop']):
    print(i)  

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


#### Arrays returned by nditer are read-only
Trying to modify this array will result in an error

In [13]:
for array in np.nditer(num):
    array[...] = array * array

ValueError: assignment destination is read-only

#### Explicitly set the array to be writeable
Use the op_flags argument to set the returned array to be read-write

In [14]:
for array in np.nditer(num, op_flags = ['readwrite']):
    array[...] = array * array

In [15]:
num

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])