In [1]:
import numpy as np

In [2]:
array_one = np.array([1,3,5,7,9])

In [3]:
array_one

array([1, 3, 5, 7, 9])

In [4]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [5]:
array.zeros(2,3)

NameError: name 'array' is not defined

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
array_zero = np.zeros((2,3))
array_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
array_ones = np.ones((3,2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
array_emp = np.empty((2,3))

In [11]:
array_emp

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
array_one = np.zeros((3,2), dtype = np.int32)

In [13]:
array_one

array([[0, 0],
       [0, 0],
       [0, 0]])

In [14]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
array_evens = np.arange(2,24,2)
array_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [16]:
array_float = np.arange(1,3,0.3)
array_float

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [17]:
array_2d = np.array([(3,4,6),(2,1,6)])
array_2d

array([[3, 4, 6],
       [2, 1, 6]])

In [18]:
array_2d.shape

(2, 3)

In [19]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
array_nd = np.arange(9).reshape(3,3)

In [24]:
array_nd

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
array_nd = np.arange(8).reshape(2,4)

In [26]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])