In [1]:
import numpy as np

In [2]:
x = np.arange(10)**3
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
for i in x:
    print(i)

0
1
8
27
64
125
216
343
512
729


In [4]:
companies = np.array([['Samsung','Microsoft','IBM','Spotify','Flipkart'],
                     [1938, 1975, 1911, 2006, 2007],
                     [489000, 131000, 380000, 3000, 30000]])
companies

array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
       ['1938', '1975', '1911', '2006', '2007'],
       ['489000', '131000', '380000', '3000', '30000']], dtype='<U9')

In [5]:
i = 0
for row in companies:
    print('Row', i, ': ', row)
    i += 1

Row 0 :  ['Samsung' 'Microsoft' 'IBM' 'Spotify' 'Flipkart']
Row 1 :  ['1938' '1975' '1911' '2006' '2007']
Row 2 :  ['489000' '131000' '380000' '3000' '30000']


In [6]:
companies.flatten()

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart', '1938',
       '1975', '1911', '2006', '2007', '489000', '131000', '380000',
       '3000', '30000'], dtype='<U9')

In [7]:
companies

array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
       ['1938', '1975', '1911', '2006', '2007'],
       ['489000', '131000', '380000', '3000', '30000']], dtype='<U9')

In [8]:
for data in companies.flatten(order = 'F'):
    print(data)

Samsung
1938
489000
Microsoft
1975
131000
IBM
1911
380000
Spotify
2006
3000
Flipkart
2007
30000


In [9]:
num = np.arange(16).reshape(4,4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
for i in np.nditer(num, order = 'F', flags = ['external_loop']):
    print(i)

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [15]:
for array in np.nditer(num, op_flags = ['readwrite']):
    array[...] = array * array

In [16]:
num

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])