## Universal Functions
A universal function (ufunc) is any function which operates on NumPy arrays in an element-by-element fashion

In [2]:
import numpy as np

#### Create a list representing the radii of a number of circles

In [3]:
circle_radii = np.array([145,120, 90, 60, 45, 30])

#### Mathematical operators which apply to each element of an array
We have performed math operations which apply to each element of an array which is an operand of the operator. Here we create a list containing the diameters for each circle in the circle_radii array

In [4]:
circle_diameters = 2 * circle_radii

circle_diameters

array([290, 240, 180, 120,  90,  60])

#### Exponential operations on an array
These can also be applied to individual elements in the NumPy array. Here, we calculate the areas of the circles

In [5]:
circle_areas = np.pi * circle_radii**2

circle_areas

array([66051.98554173, 45238.93421169, 25446.90049408, 11309.73355292,
        6361.72512352,  2827.43338823])

### Trigonometric functions in NumPy
NumPy supplies a number of trigonometric functions. They take in an NDArray as argument and apply the trigonometric operation in each individual element of the array and return an array of the same shape as the input. But before we use them, create a list with a list of angles expressed in degrees

In [6]:
angles_degrees = np.array([0, 30, 60, 90, 120, 150, 180])

#### A list of angles in radians
Trigonometric functions apply to angles expressed in radians

In [7]:
angle_radians = angles_degrees * np.pi / 180

angle_radians

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265])

#### Apply trigonometric functions on the array
We calculate the sine, cosine and tangent values for the angle_radians array

In [8]:
print('Sine values:')

np.sin(angle_radians)

Sine values:


array([0.00000000e+00, 5.00000000e-01, 8.66025404e-01, 1.00000000e+00,
       8.66025404e-01, 5.00000000e-01, 1.22464680e-16])

In [9]:
print('Cosine values:')

np.cos(angle_radians)

Cosine values:


array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
       -5.00000000e-01, -8.66025404e-01, -1.00000000e+00])

In [10]:
print('Tangent values:')

np.tan(angle_radians)

Tangent values:


array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -5.77350269e-01, -1.22464680e-16])

#### Inverse trigonometric functions
NumPy also supplies arcsin, arccos and arctan functions. We apply the arcsin function to our sine values list to recover the original angles

In [11]:
sine_values = np.sin(angle_radians)

In [12]:
arcsine_values = np.arcsin(sine_values)

arcsine_values

array([0.00000000e+00, 5.23598776e-01, 1.04719755e+00, 1.57079633e+00,
       1.04719755e+00, 5.23598776e-01, 1.22464680e-16])

In [13]:
arcsine_values * 180 / np.pi

array([0.0000000e+00, 3.0000000e+01, 6.0000000e+01, 9.0000000e+01,
       6.0000000e+01, 3.0000000e+01, 7.0167093e-15])

### Other Universal Functions
Create a new array on which to perform more operations

In [14]:
x = np.arange(4, 31, 5)

x 

array([ 4,  9, 14, 19, 24, 29])

### The exp() function
For each element x in the array, it generates an array of e<sup>x</sup> values

In [15]:
expo = np.exp(x)

expo

array([5.45981500e+01, 8.10308393e+03, 1.20260428e+06, 1.78482301e+08,
       2.64891221e+10, 3.93133430e+12])

#### The sqrt() function to calculate the square root

In [16]:
sqrt = np.sqrt(x)

sqrt

array([2.        , 3.        , 3.74165739, 4.35889894, 4.89897949,
       5.38516481])

#### Calculate the median using np.median()

In [17]:
np.median(x)

16.5

#### Load data from a file
The np.genfromtxt() function can load data into a NumPy array from a text file. Here, we load a number of floating point values from a csv file

In [18]:
float_values = np.genfromtxt('datasets/float_values.csv', delimiter =',')

In [19]:
float_values

array([0.8944, 0.8898, 0.8894, ..., 0.7051, 0.6992, 0.7047])

In [20]:
float_values.shape

(5998,)

#### Perform aggregate operations on the loaded data
The mean(), median(), var() and std() functions allow us to view statistics about our data

In [21]:
print('Mean = %i' %np.mean(float_values))

print('Median = %i' %np.median(float_values))

print('Variance = %i' %np.var(float_values))

print('Standard Deviation = %i' %np.std(float_values))

Mean = 16
Median = 5
Variance = 1659
Standard Deviation = 40
